# Generated by Django 4.2 on 2023-04-28 18:40

from django.db import migrations, models
import simplepro.components.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('create_at', simplepro.components.fields.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_at', simplepro.components.fields.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_at', simplepro.components.fields.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('create_by', simplepro.components.fields.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('detail', simplepro.components.fields.CharField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
                ('ai_name', models.CharField(blank=True, max_length=8, null=True, verbose_name='模型名称')),
                ('ai_status', models.BooleanField(default=False, verbose_name='是否启用')),
                ('ai_is_used', models.SmallIntegerField(choices=[(0, '使用异常'), (1, '未使用'), (2, '使用中')], default=0, verbose_name='使用状态')),
                ('ai_source', models.SmallIntegerField(choices=[(0, '手动添加'), (1, '平台导入')], default=0, verbose_name='模型来源')),
                ('ai_describe', models.CharField(blank=True, max_length=64, null=True, verbose_name='模型描述')),
                ('ai_file', models.FileField(blank=True, null=True, upload_to='ai', verbose_name='模型文件')),
            ],
            options={
                'verbose_name': '算法模型管理类',
                'verbose_name_plural': '算法模型管理类',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('create_at', simplepro.components.fields.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_at', simplepro.components.fields.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_at', simplepro.components.fields.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('create_by', simplepro.components.fields.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('detail', simplepro.components.fields.CharField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
                ('d_name', models.CharField(blank=True, max_length=16, null=True, verbose_name='设备名称')),
                ('d_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('d_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='设备地址')),
                ('d_geo', models.CharField(blank=True, max_length=64, null=True, verbose_name='经纬度')),
                ('d_source', models.SmallIntegerField(choices=[(0, '手动添加'), (1, '平台导入')], default=0, verbose_name='设备来源')),
                ('d_type', models.SmallIntegerField(choices=[(0, '智能摄像机'), (1, '网络摄像机')], default=0, verbose_name='设备类型')),
                ('d_brand', models.SmallIntegerField(choices=[(0, '海康'), (1, '大华'), (2, '华为'), (3, '宇视'), (4, '未知'), (5, '自定义')], default=0, verbose_name='设备品牌')),
                ('d_status', models.SmallIntegerField(choices=[(0, '离线'), (1, '在线'), (2, '异常')], default=0, verbose_name='设备状态')),
                ('d_format', models.SmallIntegerField(choices=[(0, 'RTSP'), (1, 'ONVIF'), (2, 'GB28181'), (3, 'GAT1400')], default=0, verbose_name='流类型')),
                ('d_channel', models.SmallIntegerField(default=0, verbose_name='通道号')),
                ('d_last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后一次连接时间')),
                ('d_last_logout', models.DateTimeField(blank=True, null=True, verbose_name='最后一次下线时间')),
                ('d_algorithm', models.ManyToManyField(to='device.algorithm')),
            ],
            options={
                'verbose_name': '设备视频源',
                'verbose_name_plural': '设备视频源',
            },
        ),
    ]
