# Generated by Django 4.0.3 on 2023-05-01 17:53

import django.contrib.auth.models
from django.db import migrations, models
import simplepro.components.fields
import utils.validators
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="HttpConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "create_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "delete_at",
                    simplepro.components.fields.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "create_by",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="创建人"
                    ),
                ),
                (
                    "detail",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注信息"
                    ),
                ),
                (
                    "h_status",
                    simplepro.components.fields.SwitchField(
                        default=False, verbose_name="是否启用"
                    ),
                ),
                (
                    "h_ip",
                    simplepro.components.fields.CharField(
                        max_length=16,
                        validators=[utils.validators.validate_ipv4_address],
                        verbose_name="服务器地址",
                    ),
                ),
                (
                    "h_port",
                    simplepro.components.fields.InputNumberField(verbose_name="端口"),
                ),
                (
                    "h_username",
                    simplepro.components.fields.CharField(
                        max_length=16, verbose_name="用户名"
                    ),
                ),
                (
                    "h_password",
                    simplepro.components.fields.CharField(
                        max_length=16, verbose_name="密码"
                    ),
                ),
                (
                    "h_period",
                    simplepro.components.fields.InputNumberField(
                        help_text="单位: 分钟", verbose_name="同步周期"
                    ),
                ),
            ],
            options={
                "verbose_name": "HTTP配置",
                "verbose_name_plural": "HTTP配置",
            },
        ),
        migrations.CreateModel(
            name="MqttConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "create_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "delete_at",
                    simplepro.components.fields.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "create_by",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="创建人"
                    ),
                ),
                (
                    "detail",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注信息"
                    ),
                ),
                (
                    "m_status",
                    simplepro.components.fields.SwitchField(
                        default=False, verbose_name="是否启用"
                    ),
                ),
                (
                    "m_client_id",
                    simplepro.components.fields.CharField(
                        max_length=32, verbose_name="客户端唯一标识"
                    ),
                ),
                (
                    "m_ip",
                    simplepro.components.fields.CharField(
                        max_length=16,
                        validators=[utils.validators.validate_ipv4_address],
                        verbose_name="IP地址",
                    ),
                ),
                (
                    "m_port",
                    simplepro.components.fields.InputNumberField(verbose_name="端口"),
                ),
                (
                    "m_username",
                    simplepro.components.fields.CharField(
                        max_length=16, verbose_name="用户名"
                    ),
                ),
                (
                    "m_password",
                    simplepro.components.fields.CharField(
                        max_length=16, verbose_name="密码"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mqtt配置",
                "verbose_name_plural": "Mqtt配置",
            },
        ),
        migrations.CreateModel(
            name="NetworkConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "create_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "delete_at",
                    simplepro.components.fields.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "create_by",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="创建人"
                    ),
                ),
                (
                    "detail",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注信息"
                    ),
                ),
                (
                    "n_name",
                    simplepro.components.fields.CharField(
                        max_length=16, verbose_name="网口名称"
                    ),
                ),
                (
                    "n_ip",
                    simplepro.components.fields.CharField(
                        max_length=16,
                        validators=[utils.validators.validate_ipv4_address],
                        verbose_name="IP地址",
                    ),
                ),
                (
                    "n_mask",
                    simplepro.components.fields.CharField(
                        max_length=16, verbose_name="子网掩码"
                    ),
                ),
                (
                    "n_broadcast",
                    simplepro.components.fields.CharField(
                        max_length=16, verbose_name="广播地址"
                    ),
                ),
                (
                    "n_gateway",
                    simplepro.components.fields.CharField(
                        max_length=16,
                        validators=[utils.validators.validate_ipv4_address],
                        verbose_name="默认网关",
                    ),
                ),
                (
                    "n_dns",
                    simplepro.components.fields.CharField(
                        max_length=16, verbose_name="DNS配置"
                    ),
                ),
            ],
            options={
                "verbose_name": "网络配置",
                "verbose_name_plural": "网络配置",
            },
        ),
        migrations.CreateModel(
            name="SystemInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "create_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_at",
                    simplepro.components.fields.DateTimeField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "delete_at",
                    simplepro.components.fields.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "create_by",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, null=True, verbose_name="创建人"
                    ),
                ),
                (
                    "detail",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注信息"
                    ),
                ),
                (
                    "d_type",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, verbose_name="设备型号"
                    ),
                ),
                (
                    "d_id",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, verbose_name="设备ID"
                    ),
                ),
                (
                    "d_mac",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=32, verbose_name="Mac地址"
                    ),
                ),
                (
                    "d_firmware_version",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=8, verbose_name="固件版本"
                    ),
                ),
                (
                    "d_machine_version",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=9, verbose_name="一体机版本"
                    ),
                ),
                (
                    "d_algorithm_version",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=8, verbose_name="算法软件版本"
                    ),
                ),
                (
                    "d_ffmpeg_version",
                    simplepro.components.fields.CharField(
                        blank=True, max_length=8, verbose_name="拉流软件版本"
                    ),
                ),
                (
                    "d_config",
                    simplepro.components.fields.RadioField(
                        choices=[(0, "人脸/车牌图"), (1, "行人/机动车/非机动车图"), (2, "全景图")],
                        default=0,
                        verbose_name="抓拍图片上传配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备信息",
                "verbose_name_plural": "设备信息",
            },
        ),
        migrations.CreateModel(
            name="UserProxy",
            fields=[],
            options={
                "verbose_name": "用户代理类",
                "verbose_name_plural": "用户代理类",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
